### ISSUE TITLE
go get 失败:panic: internal error: can't find reason for requirement on github.com/mattn/go-isatty@v0.0.12

### ISSUE THREAD

**Issue by mwang0** [ArtisanCloud/PowerWeChat#307]
```sh
go get -u github.com/ArtisanCloud/PowerWeChat/v3
go: downloading github.com/ArtisanCloud/PowerWeChat/v3 v3.0.31
go: downloading github.com/ArtisanCloud/PowerLibs/v3 v3.0.8
panic: internal error: can't find reason for requirement on github.com/mattn/go-isatty@v0.0.12

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc0007a3a80?, 0xc000491350?}, {0xc00011ad66?, 0xc000210e98?}})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
cmd/go/internal/modget.(*resolver).updateBuildList(0xc0005b6100, {0x16dbdf8, 0xc00011a000}, {0xc000588800, 0x20, 0x20})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x593
cmd/go/internal/modget.(*resolver).applyUpgrades(0xc0005b6100, {0x16dbdf8, 0xc00011a000}, {0xc0005d8400?, 0x20?, 0x106ee6f?})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1312 +0x105
cmd/go/internal/modget.runGet({0x16dbdf8, 0xc00011a000}, 0xc000144360?, {0xc000134030, 0x1, 0x1})
        /usr/local/go/src/cmd/go/internal/modget/get.go:351 +0x45e
main.invoke(0x19b9ac0, {0xc000134010, 0x3, 0x3})
        /usr/local/go/src/cmd/go/main.go:218 +0x2ee
main.main()
        /usr/local/go/src/cmd/go/main.go:175 +0x78e

```

**Comment by mwang0** [comment]
go env
```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xx/Library/Caches/go-build"
GOENV="/Users/xx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xx/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/xx/sdk/go1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/xx/sdk/go1.18/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xx/xx/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h2/6rx76jpn0gn437l0x29cgq600000gn/T/go-build3137033232=/tmp/go-build -gno-record-gcc-switches -fno-common"

```

**Comment by Matrix-X** [comment]
same Mac env here, too. 

<img width="896" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/58de7325-7021-4cbd-b4f3-dd00906daa7e">

Please try to upgrade your Golang version to >=1.19

**Comment by Matrix-X** [comment]
if you still get this upgrade issue after upgrading the golang version, feel free to contact us via WeCom QR code.

**Comment by cn-wang** [comment]
Thanks for the reply...
